#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["SpirePdfConvertPdfToJpgPOC/SpirePdfConvertPdfToJpgPOC.csproj", "SpirePdfConvertPdfToJpgPOC/"]
RUN dotnet restore "SpirePdfConvertPdfToJpgPOC/SpirePdfConvertPdfToJpgPOC.csproj"
COPY . .
WORKDIR "/src/SpirePdfConvertPdfToJpgPOC"
RUN dotnet build "SpirePdfConvertPdfToJpgPOC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SpirePdfConvertPdfToJpgPOC.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SpirePdfConvertPdfToJpgPOC.dll"]